$INC_CORE_DIR/riscv_pkg.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_pkg.sv 
$INC_CORE_DIR/drac_pkg.sv
$INC_CORE_DIR/def_pkg.sv

$SRC_DATAPATH_DIR/exe_stage/rtl/simd/div_2bits.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vaddsub.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vcomp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vdiv.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vfirst.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/viota.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vmsb_i_o_f.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vmul.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vnclip.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vpopc.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vredtree.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vsaaddsub.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vshift.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vsmul.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vwaddsub.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vmconv_ctrl.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/functional_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/simd_unit.sv
