$SRC_CORE_DIR/common_cells/include/common_cells/registers.svh
$SRC_CORE_DIR/common_cells/include/common_cells/assertions.svh
$SRC_CORE_DIR/common_cells/src/cf_math_pkg.sv
$SRC_CORE_DIR/common_cells/src/lzc.sv
$SRC_CORE_DIR/common_cells/src/fifo_v3.sv
$SRC_CORE_DIR/common_cells/src/rr_arb_tree.sv
$SRC_CORE_DIR/common_cells/src/exp_backoff.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_pkg.sv
$INC_CORE_DIR/riscv_pkg.sv
$INC_CORE_DIR/def_pkg.sv
$INC_CORE_DIR/drac_pkg.sv
$SRC_CORE_DIR/register.sv

$SRC_CORE_DIR/mmu/includes/mmu_pkg.sv
$SRC_CORE_DIR/mmu/rtl/common/pseudoLRU.sv
$SRC_CORE_DIR/mmu/rtl/ptw/ptw_arb.sv
$SRC_CORE_DIR/mmu/rtl/ptw/ptw.sv
$SRC_CORE_DIR/mmu/rtl/tlb/tlb.sv
$SRC_CORE_DIR/mmu/rtl/bsc_mmu.sv

$SRC_CORE_DIR/control_unit/rtl/control_unit.sv
$SRC_DATAPATH_DIR/interface_csr/rtl/csr_interface.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/load_store_queue.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vshift.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/div_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/pending_mem_req_queue.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/defs_div_sqrt_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/control_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/div_sqrt_top_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/iteration_div_sqrt_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/norm_div_sqrt_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/nrbd_nrsc_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_div_sqrt/preprocess_mvp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_cast_multi.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_classifier.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_divsqrt_multi.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_divsqrt_th_32.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_fma.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_fma_multi.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_noncomp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_opgroup_block.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_opgroup_fmt_slice.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_opgroup_multifmt_slice.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_rounding.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpnew_top.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/fpu/fpu_drac_wrapper.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/alu.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/alu_add.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/alu_shift.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/alu_logic.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/alu_cmp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/zero_counter/alu_count_zeros.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/zero_counter/alu_count_zeros_BNE.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/zero_counter/alu_count_zeros_NLC.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/zero_counter/alu_count_zeros_LZC32.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/alu/alu_count_pop.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/exe_stage.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/branch_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vmconv_ctrl.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/functional_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vcomp.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vredtree.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vmul.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vpopc.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/viota.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vfirst.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vmsb_i_o_f.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vdiv.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/div_2bits.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/pending_fp_ops_queue.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/score_board_scalar.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/score_board_simd.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/mul_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/mem_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/simd_unit.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vaddsub.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vsaaddsub.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vwaddsub.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vnclip.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/simd/vsmul.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/div_4bits.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/store_buffer.sv
$SRC_DATAPATH_DIR/exe_stage/rtl/vagu.sv
$SRC_DATAPATH_DIR/if_stage_1/rtl/bimodal_predictor.sv
$SRC_DATAPATH_DIR/if_stage_1/rtl/return_address_stack.sv
$SRC_DATAPATH_DIR/if_stage_1/rtl/branch_predictor.sv
$SRC_DATAPATH_DIR/if_stage_1/rtl/if_stage_1.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/simd_rename_table.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/fp_rename_table.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/simd_free_list.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/fp_free_list.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/free_list.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/instruction_queue.sv
$SRC_DATAPATH_DIR/ir_stage/rtl/rename_table.sv
$SRC_DATAPATH_DIR/if_stage_2/rtl/if_stage_2.sv
$SRC_DATAPATH_DIR/id_stage/rtl/immediate.sv
$SRC_DATAPATH_DIR/id_stage/rtl/decoder.sv
$SRC_DATAPATH_DIR/id_stage/rtl/vset_module.sv
$SRC_DATAPATH_DIR/id_stage/rtl/vset_queue.sv
$SRC_DATAPATH_DIR/rr_stage/rtl/regfile.sv
$SRC_DATAPATH_DIR/rr_stage/rtl/vregfile.sv
$SRC_DATAPATH_DIR/rr_stage/rtl/regfile_fp.sv
$SRC_DATAPATH_DIR/wb_stage/rtl/graduation_list.sv

$SRC_DATAPATH_DIR/datapath.sv